# Generated by Django 5.0.6 on 2024-08-24 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookuser',
            old_name='service',
            new_name='services',
        ),
    ]
