# Generated by Django 5.0.6 on 2024-08-23 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_dentist_bookuser_doctor_remove_bookuser_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookuser',
            name='services',
        ),
        migrations.AddField(
            model_name='bookuser',
            name='service',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bookuser',
            name='time',
            field=models.TimeField(default=datetime.time(11, 52, 31, 822142)),
        ),
        migrations.AlterField(
            model_name='bookuser',
            name='doctor',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
