# Generated by Django 5.0.6 on 2024-08-20 15:11

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_doctor_availability_remove_doctor_speciality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='appointment_date',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='availability',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='doctor',
            name='name',
            field=models.CharField(default='Uknowny', max_length=255),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
